version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - REDIS_URL=redis://redis:6379/1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"